spring.application.name=UserService

server.port = 9090

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}

spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=none

applog.dir=D:\\Data\\EcommerceWorkspace\\logs\\userservice