spring.application.name=UserService

server.port = 9090

spring.datasource.url=jdbc:postgresql://localhost:5432/ecom
spring.datasource.username=postgres
spring.datasource.password=vitthal@2003

spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=none

applog.dir=D:\\Data\\EcommerceWorkspace\\logs\\userservice